### ISSUE TITLE
Unbounded / mesh export?

### ISSUE THREAD

**Issue by antithing** [Bariona/GH-NeRF#1]
Hi! and thank you for making this code available, it works great on the LLFF data.

Two questions:
1. Will it work as well on unbounded scenes? 
2. Is there any way to export a textured mesh?

Thanks!

**Comment by Bariona** [comment]
Hi there
1. I don't think there is much difference in the performance if you transfer the coordinates into NDC.

2. The current version doesn't support mesh extraction. I may add this feature this week or later.

Thanks for your helpful questions.
